"""SendGrid email alert sender for ShadowLense."""

from typing import Any

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail


def send_alert(
    api_key: str,
    from_email: str,
    to_email: str,
    domain: str,
    threats: list[dict[str, Any]],
) -> bool:
    """Send an HTML threat alert email via SendGrid.

    Returns True on success, False on any failure.
    """
    rows = ""
    for t in threats:
        rows += (
            f"<tr>"
            f"<td style='padding:6px 12px;border:1px solid #ddd'>{t.get('category', '')}</td>"
            f"<td style='padding:6px 12px;border:1px solid #ddd'>{t.get('severity', '')}</td>"
            f"<td style='padding:6px 12px;border:1px solid #ddd'>{t.get('ioc_type', '')}</td>"
            f"<td style='padding:6px 12px;border:1px solid #ddd'>{t.get('ai_summary', '')}</td>"
            f"</tr>"
        )

    html_content = f"""
    <html><body>
    <h2>ShadowLense Threat Alert — {domain}</h2>
    <p>The following threat intelligence records reference <strong>{domain}</strong>:</p>
    <table style='border-collapse:collapse;font-family:monospace;font-size:13px'>
      <thead>
        <tr style='background:#f4f4f4'>
          <th style='padding:6px 12px;border:1px solid #ddd'>Category</th>
          <th style='padding:6px 12px;border:1px solid #ddd'>Severity</th>
          <th style='padding:6px 12px;border:1px solid #ddd'>IOC Type</th>
          <th style='padding:6px 12px;border:1px solid #ddd'>Summary</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
    <p style='color:#888;font-size:11px'>Generated by ShadowLense</p>
    </body></html>
    """

    message = Mail(
        from_email=from_email,
        to_emails=to_email,
        subject=f"[ShadowLense] Threat detected for {domain}",
        html_content=html_content,
    )

    try:
        client = SendGridAPIClient(api_key)
        response = client.send(message)
        return response.status_code in (200, 202)
    except Exception:
        return False
